package:
  name: pyIsoP_1.0
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - pyIsoP_1.0

about:
  home: add_url_here
  license: BSD-3-Clause License
